# Generated by Django 4.2.3 on 2023-07-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_orderitem_order_productimagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImageModel',
            new_name='ProductImage',
        ),
    ]
